name: fetch
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *' # 每 3 小时执行一次

jobs:
  fetchurl:
    runs-on: ubuntu-latest
    env:
      USERID: ${{ secrets.USERID }}
      MIGU_TOKEN: ${{ secrets.MIGU_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmmirror.com
          npm install

      - name: Fetch Android Video URLs
        run: |
          node fetchURLByAndroid.js

      - name: Commit and Push updated IPTV file
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add all_channels.m3u
          git diff --quiet || git commit -m "Update all_channels.m3u by GitHub Actions"
          git push
